PREFIX = "/video/kayosports"
ART = "logo.png"
ICON = "art-default.png"
NAME = "Kayo Sports"
AUTH_URL = "https://auth.kayosports.com.au/oauth/token"
PROFILES_URL = "https://profileapi.kayosports.com.au/user/profile"
LIVE_EVENTS_URL = "https://vccapi.kayosports.com.au/v2/content/types/landing/names/sports?evaluate=3&profile=${profileId}"
STREAM_URL = "https://vmndplay.kayosports.com.au/api/v1/asset/${streamId}/play.json?fields=alternativeStreams"
CLIENT_ID = "qjmv9ZvaMDS9jGvHOxVfImLgQ3G5NrT2"
